=== jayniz/blumquist/spec/support/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": ["string", "null"] }
      },
      "required": ["street_address", "city", "state"]
    },
    "sibling": {
      "type": "object",
      "properties": {
        "age_difference": { "type": "number" },
        "name":           { "type": "string" }
      },
      "required": ["age_difference", "name"]
    },
    "ancestor": {
      "type": "object",
      "properties": {
        "family_name":      { "type": "string" }
      },
      "required": ["family_name"]
    }
  },

  "type": "object",

  "properties": {
    "name": { "type": "string", "maxLength": 16 },
    "phone_numbers": {
      "type": "array",
      "items": [{ "type": "object", "properties": { "prefix": {"type" :"number"}, "extension": {"type": "number"} }}]
    },
    "current_address": {
      "oneOf": [
        { "type": "null" },
        {"$ref": "#/definitions/address" },
        {
          "type": "object",
          "properties": {
            "planet": { "type" : "string" }
          },
          "required": ["planet"]
        }
      ]
    },
    "relatives": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/definitions/sibling"
          },
          {
            "$ref": "#/definitions/ancestor"
          }
        ]
      }
    },
    "old_addresses": {
      "type": "array",
      "items": [{ "$ref": "#/definitions/address"}]
    }
  }
}

=== jayniz/blumquist/spec/support/data.json
{
  "name": "Moviepilot, Inc.",
  "phone_numbers": [{"prefix": 555, "extension": 1234}],
  "current_address": {
    "street_address": "Chausseestr. 111",
    "city": "Berlin",
    "state": "Berlin"
  },
  "old_addresses": [
    {
      "street_address": "Friedrichstr. 58",
      "city": "Berlin",
      "state": "Berlin"
    },
    {
      "street_address": "Mehringdamm 33",
      "city": "Berlin",
      "state": "Berlin"
    },
    {
      "street_address": "Bluecherstr. 22",
      "city": "Berlin",
      "state": "Berlin"
    }
  ]
}
